// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjqxia0FFFbusUa65uaC1PwMOAz0BNNho',
    appId: '1:713569652280:web:aaeb906a19d06a120fa0cd',
    messagingSenderId: '713569652280',
    projectId: 'melodeia-sleep',
    authDomain: 'melodeia-sleep.firebaseapp.com',
    storageBucket: 'melodeia-sleep.firebasestorage.app',
    measurementId: 'G-ZDV5MB3LBF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUG2aW65gB8CU9kFuBAnsmDpW2_CUv7QE',
    appId: '1:713569652280:android:f6ec3f9151bd6d880fa0cd',
    messagingSenderId: '713569652280',
    projectId: 'melodeia-sleep',
    storageBucket: 'melodeia-sleep.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgOKdhDdE5AEbR3nsrNqEhnFfwvBEIA58',
    appId: '1:713569652280:ios:99b1f353a18958070fa0cd',
    messagingSenderId: '713569652280',
    projectId: 'melodeia-sleep',
    storageBucket: 'melodeia-sleep.firebasestorage.app',
    iosBundleId: 'com.example.melodeiaSleepApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgOKdhDdE5AEbR3nsrNqEhnFfwvBEIA58',
    appId: '1:713569652280:ios:99b1f353a18958070fa0cd',
    messagingSenderId: '713569652280',
    projectId: 'melodeia-sleep',
    storageBucket: 'melodeia-sleep.firebasestorage.app',
    iosBundleId: 'com.example.melodeiaSleepApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjqxia0FFFbusUa65uaC1PwMOAz0BNNho',
    appId: '1:713569652280:web:4abb4e3f60cd557c0fa0cd',
    messagingSenderId: '713569652280',
    projectId: 'melodeia-sleep',
    authDomain: 'melodeia-sleep.firebaseapp.com',
    storageBucket: 'melodeia-sleep.firebasestorage.app',
    measurementId: 'G-3KSKTP3XMX',
  );
}
